import type { Metadata } from "next";
import "./globals.css";
import { luckiestGuy } from "@/components/settings-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased overflow-hidden ${luckiestGuy}`}
      >
        {children}
      </body>
    </html>
  );
}
